apiVersion: apps/v1
kind: Deployment
metadata:
  name: pabackend-deployment
  labels:
    app: pabackend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pabackend
  template:
    metadata:
      labels:
        app: pabackend
    spec:
      containers:
      - name: pabackend
        image: salinasmiguelg/pabackend
        imagePullPolicy: Always
        ports:
        -name: http
        - containerPort: 8086
